SELECT HOUR
     , COUNT
  FROM (
    SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) HOUR
         , COUNT(1) AS COUNT
      FROM ANIMAL_OUTS
    GROUP BY TO_CHAR(DATETIME, 'HH24')
  )
 WHERE HOUR BETWEEN 9 AND 20
ORDER BY HOUR