SELECT CATEGORY
     , SUM(SALES) AS TOTAL_SALES
  FROM BOOK B
   LEFT OUTER JOIN BOOK_SALES BS
     ON B.BOOK_ID = BS.BOOK_ID
 WHERE TO_CHAR(SALES_DATE, 'YYYYMM') = '202201'
GROUP BY CATEGORY
ORDER BY CATEGORY ASC